version: 2
jobs:
  build:
    docker:
      - image: swift:latest
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test

